import { SystemSettingsService } from './SystemSettingsService';

const GEMINI_API_KEY = (import.meta.env.VITE_GEMINI_API_KEY || '').trim();
const GEMINI_MODEL = (import.meta.env.VITE_GEMINI_MODEL || 'gemini-1.5-flash').trim();

export interface GeneratedQuestion {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface TestGenerationParams {
  subject: string;
  chapter: string;
  topic: string;
  numQuestions: number;
  difficulty: 'easy' | 'medium' | 'hard' | 'mixed';
  questionTypes?: ('mcq' | 'truefalse' | 'fillblank')[];
}

export interface PromptBasedTestGenerationParams {
  subject: string;
  chapter?: string;
  prompt: string;
  numQuestions: number;
  difficulty: 'easy' | 'medium' | 'hard' | 'mixed';
}

export interface SubjectBlueprint {
  subjects: Array<{
    name: string;
    description: string;
    grade: number;
    chapters: Array<{
      name: string;
      description: string;
      content: string;
    }>;
  }>;
}

const extractJsonObject = (text: string): any => {
  const cleaned = text.replace(/```json|```/gi, '').trim();
  const match = cleaned.match(/\{[\s\S]*\}/);
  if (!match) {
    throw new Error('Could not parse JSON object from AI response');
  }
  return JSON.parse(match[0]);
};

export interface TutorMessage {
  role: 'user' | 'model';
  content: string;
}

export type TutorMode = 'simple' | 'teacher' | 'exam' | 'quiz';

const callGroq = async (prompt: string, messages: TutorMessage[], settings: any): Promise<string> => {
  const apiKey = settings.groq_api_key || import.meta.env.VITE_GROQ_API_KEY;
  if (!apiKey) throw new Error('Groq API Key not configured');

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: settings.groq_model || 'llama-3.1-70b-versatile',
      messages: [
        ...messages.map(m => ({ role: m.role === 'model' ? 'assistant' : 'user', content: m.content })),
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
      max_tokens: 2048,
    }),
  });

  const rawText = await response.text();
  if (!response.ok) throw new Error(`Groq API Error: ${response.status} - ${rawText}`);
  
  const data = JSON.parse(rawText);
  return data.choices?.[0]?.message?.content || '';
};

const callIntelligence = async (prompt: string, previousMessages: TutorMessage[] = []): Promise<string> => {
  const settings = await SystemSettingsService.getSettings();
  
  if (settings.ai_provider === 'groq') {
    return callGroq(prompt, previousMessages, settings);
  }
  
  const contents = [
    ...previousMessages.map(m => ({
      role: m.role === 'model' ? 'model' : 'user',
      parts: [{ text: m.content }]
    })),
    { role: 'user', parts: [{ text: prompt }] }
  ];

  return callGemini(contents, { temperature: 0.7, maxOutputTokens: 2048 }, settings);
};

const callGemini = async (
  contents: Array<{ role?: string; parts: Array<{ text: string }> }>,
  generationConfig: { temperature: number; maxOutputTokens: number },
  settings?: any
): Promise<string> => {
  const apiKey = settings?.gemini_api_key || GEMINI_API_KEY;
  const modelName = settings?.gemini_model || GEMINI_MODEL;
  
  if (!apiKey) {
    throw new Error('Gemini API key is not configured');
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ contents, generationConfig }),
  });

  const raw = await response.text();
  let data: any = {};

  if (raw) {
    try {
      data = JSON.parse(raw);
    } catch {
      throw new Error('Gemini returned invalid JSON response');
    }
  }

  if (!response.ok) {
    const message =
      data?.error?.message || `Gemini API error: ${response.status}`;
    throw new Error(message);
  }

  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error('No content generated by Gemini');
  }

  return String(text).trim();
};

// Generate test questions using Gemini Flash API
export const generateTestQuestions = async (
  params: TestGenerationParams
): Promise<GeneratedQuestion[]> => {
  try {
    const prompt = `
You are an expert educational content creator. Generate ${params.numQuestions} multiple choice questions for the following:

Subject: ${params.subject}
Chapter: ${params.chapter}
Topic: ${params.topic}
Difficulty Level: ${params.difficulty}

For each question, provide:
1. A clear, concise question
2. Exactly 4 answer options (A, B, C, D)
3. The correct answer index (0 for A, 1 for B, 2 for C, 3 for D)
4. A brief explanation of why the answer is correct
5. Difficulty level (easy, medium, or hard)

Format your response as a valid JSON array with this exact structure:
[
  {
    "question": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswer": 0,
    "explanation": "Explanation of the correct answer",
    "difficulty": "easy"
  }
]

Important: Return ONLY the JSON array, no markdown formatting, no additional text.
`;

    const text = await callGemini(
      [
        {
          parts: [{ text: prompt }],
        },
      ],
      {
        temperature: 0.7,
        maxOutputTokens: 8192,
      }
    );

    // Extract JSON from the response
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      throw new Error('Could not parse generated questions');
    }

    const questions: GeneratedQuestion[] = JSON.parse(jsonMatch[0]);

    // Validate and sanitize questions
    return questions.map((q, index) => ({
      question: q.question || `Question ${index + 1}`,
      options: q.options?.length === 4 ? q.options : ['Option A', 'Option B', 'Option C', 'Option D'],
      correctAnswer: typeof q.correctAnswer === 'number' && q.correctAnswer >= 0 && q.correctAnswer <= 3
        ? q.correctAnswer
        : 0,
      explanation: q.explanation || 'No explanation provided',
      difficulty: ['easy', 'medium', 'hard'].includes(q.difficulty) ? q.difficulty : 'medium',
    }));
  } catch (error) {
    console.error('Error generating test questions:', error);
    // Return fallback questions if API fails
    return generateFallbackQuestions(params.numQuestions);
  }
};

export const generateTestQuestionsFromPrompt = async (
  params: PromptBasedTestGenerationParams
): Promise<GeneratedQuestion[]> => {
  try {
    const prompt = `
You are an expert school teacher. Generate ${params.numQuestions} MCQs based on this teacher instruction:
"${params.prompt}"

Context:
Subject: ${params.subject}
Chapter: ${params.chapter || 'Not specified'}
Difficulty: ${params.difficulty}

Return a strict JSON array only:
[
  {
    "question": "Question text",
    "options": ["A", "B", "C", "D"],
    "correctAnswer": 0,
    "explanation": "Why this answer is correct",
    "difficulty": "easy"
  }
]

Rules:
- Exactly 4 options per question
- correctAnswer must be 0,1,2,3
- Keep language classroom-friendly
- No markdown, no extra text, JSON only
`;

    const text = await callGemini(
      [{ parts: [{ text: prompt }] }],
      {
        temperature: 0.6,
        maxOutputTokens: 8192,
      }
    );

    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      throw new Error('Could not parse prompt-based generated questions');
    }

    const questions: GeneratedQuestion[] = JSON.parse(jsonMatch[0]);
    return questions.map((q, index) => ({
      question: q.question || `Question ${index + 1}`,
      options: q.options?.length === 4 ? q.options : ['Option A', 'Option B', 'Option C', 'Option D'],
      correctAnswer:
        typeof q.correctAnswer === 'number' && q.correctAnswer >= 0 && q.correctAnswer <= 3
          ? q.correctAnswer
          : 0,
      explanation: q.explanation || 'No explanation provided',
      difficulty: ['easy', 'medium', 'hard'].includes(q.difficulty) ? q.difficulty : 'medium',
    }));
  } catch (error) {
    console.error('Error generating prompt-based test questions:', error);
    return generateFallbackQuestions(params.numQuestions);
  }
};

export const generateSubjectBlueprint = async (
  params: { prompt: string; sourceText?: string }
): Promise<SubjectBlueprint> => {
  const normalizeBlueprint = (parsed: SubjectBlueprint): SubjectBlueprint => {
    if (!parsed.subjects || !Array.isArray(parsed.subjects) || parsed.subjects.length === 0) {
      throw new Error('Blueprint did not contain subjects');
    }
    return {
      subjects: parsed.subjects.map((subject, subjectIndex) => ({
        name: subject.name || `Subject ${subjectIndex + 1}`,
        description: subject.description || 'Generated subject',
        grade: typeof subject.grade === 'number' ? Math.min(12, Math.max(1, subject.grade)) : 10,
        chapters: (subject.chapters || []).map((chapter, chapterIndex) => ({
          name: chapter.name || `Chapter ${chapterIndex + 1}`,
          description: chapter.description || 'Generated chapter',
          content: chapter.content || chapter.description || 'Generated content',
        })),
      })),
    };
  };

  try {
    // Prefer server endpoint so deployment secrets can be used even without VITE_GEMINI_API_KEY.
    try {
      const response = await fetch('/api/ai/subject-blueprint', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: params.prompt,
          sourceText: params.sourceText,
        }),
      });

      if (response.ok) {
        const raw = await response.text();
        const data = raw ? JSON.parse(raw) : {};
        const parsed = extractJsonObject(String(data?.text || ''));
        return normalizeBlueprint(parsed as SubjectBlueprint);
      }
    } catch (serverError) {
      console.warn('Server AI subject generation failed, falling back to client Gemini:', serverError);
    }

    const prompt = `
You are an academic curriculum designer.

Teacher/Admin instruction:
${params.prompt}

Reference text extracted from uploaded material:
${params.sourceText?.slice(0, 12000) || 'No extra source text provided.'}

Generate a JSON object in this exact structure:
{
  "subjects": [
    {
      "name": "Subject Name",
      "description": "Short description",
      "grade": 10,
      "chapters": [
        {
          "name": "Chapter Name",
          "description": "Chapter description",
          "content": "High-level summary content"
        }
      ]
    }
  ]
}

Rules:
- 1 to 5 subjects
- Each subject should have 3 to 12 chapters
- Return JSON only, no markdown
`;

    const text = await callGemini(
      [{ parts: [{ text: prompt }] }],
      {
        temperature: 0.5,
        maxOutputTokens: 8192,
      }
    );

    const parsed = extractJsonObject(text) as SubjectBlueprint;
    return normalizeBlueprint(parsed);
  } catch (error) {
    console.error('Error generating subject blueprint:', error);
    return {
      subjects: [
        {
          name: 'Generated Subject',
          description: 'Auto-generated subject outline',
          grade: 10,
          chapters: [
            {
              name: 'Chapter 1',
              description: 'Auto-generated chapter',
              content: params.prompt || 'Generated content',
            },
          ],
        },
      ],
    };
  }
};

// AI Tutor - Get response from Gemini
const getModeSystemPrompt = (mode: TutorMode): string => {
  const commonInstructions = `
Language Rules: 
- If providing Hindi examples, provide the Hindi script (Devanagari) first, then the English translation.
- IMPORTANT: DO NOT provide Romanized/Phonetic Hindi in brackets (e.g. avoid "(Main kahan ja raha hoon)") as it confuses the speech system.

CRITICAL FORMATTING RULES:
You MUST structure your response EXACTLY using these three Markdown headers:
## Explanation
(Provide the main explanation, answer, or quiz question here)

## Example
(Provide a concrete example or analogy here)

## Key Points
(Provide 1-3 short bullet points summarizing the takeaway or hint)

Do not add any conversational filler before the first header.
`;

  switch (mode) {
    case 'simple':
      return `You are a friendly AI tutor. ${commonInstructions} Explain concepts in the simplest possible language. Use short sentences, everyday analogies, and avoid jargon. Use bullet points for key facts and give one relatable example. Keep the response concise (under 200 words).`;
    case 'teacher':
      return `You are an experienced school teacher. ${commonInstructions} Give structured, detailed explanations. Start with a brief introduction, use numbered steps or bullet points, provide examples, and end with a summary or key takeaway. Use diagrams descriptions where helpful.`;
    case 'exam':
      return `You are an exam preparation expert. ${commonInstructions} Focus on key points likely to appear in exams. Use bullet points for important concepts, highlight formulas or definitions with emphasis, mention common mistakes, and provide 1-2 typical exam-style practice questions at the end.`;
    case 'quiz':
      return `You are a quiz master. ${commonInstructions} Instead of directly explaining, ask the student a question about the topic to test their understanding. If they answer correctly, congratulate them and ask a harder follow-up. If they answer incorrectly, gently explain the correct answer and ask an easier question. Always be encouraging.`;
    default:
      return `You are a helpful and knowledgeable AI tutor. ${commonInstructions} Provide clear, well-structured explanations with examples.`;
  }
};

export const getTutorResponse = async (
  message: string,
  context?: {
    subject?: string;
    chapter?: string;
    previousMessages?: TutorMessage[];
    mode?: TutorMode;
  }
): Promise<string> => {
  try {
    // Try server endpoint first
    try {
      const response = await fetch('/api/ai/tutor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message, context }),
      });

      if (response.ok) {
        const raw = await response.text();
        const data = raw ? JSON.parse(raw) : {};
        const text = typeof data?.text === 'string' ? data.text : '';
        if (text.trim()) return text.trim();
      }
    } catch {
      // Server endpoint failed, fall through to client-side Gemini
    }

    // Client-side AI call with mode-specific prompt
    const mode = context?.mode || 'teacher';
    const systemPrompt = getModeSystemPrompt(mode);

    const contextParts = [];
    if (context?.subject) contextParts.push(`Subject: ${context.subject}`);
    if (context?.chapter) contextParts.push(`Chapter: ${context.chapter}`);

    const prompt = `${systemPrompt}\n\n${contextParts.length ? contextParts.join('\n') + '\n\n' : ''}Student's question: ${message}`;
    const previousMessages = context?.previousMessages?.slice(-5) || [];

    const text = await callIntelligence(prompt, previousMessages);
    return text;
  } catch (error) {
    console.error('Error getting tutor response:', error);
    return getFallbackTutorResponse(message);
  }
};

// Generate study plan using AI
export const generateStudyPlan = async (
  params: {
    subjects: string[];
    availableHoursPerDay: number;
    totalDays: number;
    goals: string;
    currentLevel: 'beginner' | 'intermediate' | 'advanced';
  }
): Promise<{
  title: string;
  description: string;
  dailySchedule: {
    day: number;
    subject: string;
    topics: string[];
    duration: number;
    activities: string[];
  }[];
}> => {
  try {
    const prompt = `
Create a personalized study plan with the following parameters:

Subjects: ${params.subjects.join(', ')}
Available Hours Per Day: ${params.availableHoursPerDay}
Total Days: ${params.totalDays}
Student's Goals: ${params.goals}
Current Level: ${params.currentLevel}

Generate a detailed study plan with daily schedules. Format as JSON:

{
  "title": "Study Plan Title",
  "description": "Brief description of the plan",
  "dailySchedule": [
    {
      "day": 1,
      "subject": "Subject Name",
      "topics": ["Topic 1", "Topic 2"],
      "duration": 60,
      "activities": ["Activity 1", "Activity 2"]
    }
  ]
}

Return ONLY the JSON object, no markdown formatting.
`;

    const text = await callGemini(
      [
        {
          parts: [{ text: prompt }],
        },
      ],
      {
        temperature: 0.7,
        maxOutputTokens: 4096,
      }
    );

    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Could not parse study plan');
    }

    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error('Error generating study plan:', error);
    return generateFallbackStudyPlan(params);
  }
};

// Analyze weak areas based on test performance
export const analyzeWeakAreas = async (
  testResults: {
    subject: string;
    chapter: string;
    topic: string;
    score: number;
    totalQuestions: number;
    correctAnswers: number;
  }[]
): Promise<{
  weakAreas: { subject: string; chapter: string; topic: string; mastery: number }[];
  recommendations: string[];
}> => {
  try {
    const prompt = `
Analyze the following test performance data and identify weak areas:

${JSON.stringify(testResults, null, 2)}

Provide:
1. A list of weak areas with mastery percentage (0-100)
2. Personalized recommendations for improvement

Format as JSON:
{
  "weakAreas": [
    { "subject": "Subject", "chapter": "Chapter", "topic": "Topic", "mastery": 45 }
  ],
  "recommendations": ["Recommendation 1", "Recommendation 2"]
}

Return ONLY the JSON object.
`;

    const text = await callGemini(
      [{ parts: [{ text: prompt }] }],
      {
        temperature: 0.5,
        maxOutputTokens: 2048,
      }
    );

    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Could not parse analysis');
    }

    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error('Error analyzing weak areas:', error);
    return generateFallbackWeakAreaAnalysis(testResults);
  }
};

// Fallback functions for when API fails
const generateFallbackQuestions = (count: number): GeneratedQuestion[] => {
  const questions: GeneratedQuestion[] = [];
  for (let i = 0; i < count; i++) {
    questions.push({
      question: `Sample Question ${i + 1}: What is the correct answer?`,
      options: ['Option A', 'Option B', 'Option C', 'Option D'],
      correctAnswer: 0,
      explanation: 'This is a sample explanation for the correct answer.',
      difficulty: 'medium',
    });
  }
  return questions;
};

const getFallbackTutorResponse = (_message: string): string => {
  const responses = [
    "That's a great question! Let me explain this concept in detail. The key to understanding this topic is to break it down into smaller, manageable parts. Start by identifying the main concepts and then explore how they connect to each other.",
    "I understand your question. This is an important topic that builds on several fundamental concepts. Let me walk you through it step by step. First, let's establish the basics, then we'll dive deeper into the more complex aspects.",
    "Excellent question! This concept can be tricky at first, but once you grasp the underlying principles, it becomes much clearer. Think of it this way: imagine you're building a house - you need a strong foundation before you can add the walls and roof.",
  ];
  return responses[Math.floor(Math.random() * responses.length)];
};

const generateFallbackStudyPlan = (params: any) => {
  const dailySchedule = [];
  for (let i = 1; i <= params.totalDays; i++) {
    const subject = params.subjects[i % params.subjects.length];
    dailySchedule.push({
      day: i,
      subject,
      topics: [`Topic ${i} for ${subject}`],
      duration: params.availableHoursPerDay * 60,
      activities: ['Read chapter', 'Practice problems', 'Review notes'],
    });
  }

  return {
    title: `Personalized ${params.totalDays}-Day Study Plan`,
    description: `A customized study plan focusing on ${params.subjects.join(', ')}`,
    dailySchedule,
  };
};

const generateFallbackWeakAreaAnalysis = (testResults: any[]) => {
  const weakAreas = testResults
    .filter(r => r.score < 70)
    .map(r => ({
      subject: r.subject,
      chapter: r.chapter,
      topic: r.topic,
      mastery: r.score,
    }));

  return {
    weakAreas,
    recommendations: [
      'Review the fundamental concepts in your weak areas',
      'Practice more problems from these topics',
      'Create flashcards for key terms and formulas',
      'Watch educational videos on these subjects',
      'Form a study group to discuss difficult concepts',
    ],
  };
};

// Voice Practice AI Feedback
export const getVoicePracticeFeedback = async (
  expectedText: string,
  spokenText: string,
  scores: { pronunciation: number; fluency: number; clarity: number; wpm: number; targetWpm: number }
): Promise<{ tips: string[]; syllableHints: string; overallComment: string }> => {
  try {
    const prompt = `You are a pronunciation coach. A student tried to say:
"${expectedText}"

They actually said:
"${spokenText}"

Scores: Pronunciation ${scores.pronunciation}%, Fluency ${scores.fluency}%, Clarity ${scores.clarity}%, Speed ${scores.wpm} WPM (target: ${scores.targetWpm} WPM)

Give feedback as JSON:
{
  "tips": ["Specific tip 1", "Specific tip 2"],
  "syllableHints": "Show correct stress pattern e.g. com-mu-ni-CA-tion",
  "overallComment": "One encouraging sentence about their performance"
}
Return ONLY JSON, no markdown.`;

    const text = await callGemini(
      [{ parts: [{ text: prompt }] }],
      { temperature: 0.6, maxOutputTokens: 1024 }
    );

    const parsed = extractJsonObject(text);
    return {
      tips: Array.isArray(parsed.tips) ? parsed.tips : ['Keep practicing!'],
      syllableHints: parsed.syllableHints || '',
      overallComment: parsed.overallComment || 'Good effort! Keep it up!',
    };
  } catch (error) {
    console.error('Error getting voice feedback:', error);
    return {
      tips: ['Focus on pronouncing each syllable clearly', 'Try speaking at a steady pace'],
      syllableHints: '',
      overallComment: 'Good effort! Keep practicing to improve.',
    };
  }
};

// Translate content directly using Unofficial Google API (Gtx - Free)
export const freeTranslate = async (text: string, targetLanguage: 'hi' | 'en'): Promise<string> => {
  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${targetLanguage}&dt=t&q=${encodeURIComponent(text)}`;
    const response = await fetch(url);
    if (!response.ok) throw new Error('Free Translation service unavailable');
    const data = await response.json();
    // data[0] contains translated segments
    if (data && data[0]) {
      return data[0].map((s: any) => s[0]).join('');
    }
    throw new Error('Invalid response format');
  } catch (error) {
    console.error('Free translation error:', error);
    throw error;
  }
};

// Main translation entry point
export const translateContent = async (text: string, targetLanguage: 'hi' | 'en'): Promise<string> => {
  // Always try free translation first for "Beginner / Free App" mode
  try {
    return await freeTranslate(text, targetLanguage);
  } catch (freeError) {
    console.warn('Free translation failed, falling back to Gemini if configured...', freeError);
    
    // Fallback to Gemini if free fails
    try {
      const prompt = `Translate the following educational content to ${targetLanguage === 'hi' ? 'Hindi' : 'English'}.
Preserve ALL the original formatting, including paragraphs, bullet points, headers, and symbols.
Do not add any additional explanations or intro text. Just the translated content.
If the text contains mathematical or scientific formulas, keep them intact or translate surrounding words appropriately.

Content to translate:
${text}`;

      return await callIntelligence(prompt);
    } catch (error: any) {
      console.error('Translation error:', error);
      throw new Error(error.message || 'Failed to translate content');
    }
  }
};

export default {
  generateTestQuestions,
  generateTestQuestionsFromPrompt,
  generateSubjectBlueprint,
  getTutorResponse,
  generateStudyPlan,
  analyzeWeakAreas,
  getVoicePracticeFeedback,
  translateContent,
  freeTranslate,
};
